### ISSUE TITLE
cachedDataRejected on electron when build to 32bit version

### ISSUE THREAD

**Issue by alonado** [OsamaAbbas/bytenode#98] opened 2021-01-11 15:10 UTC
Hey!

This is a great repo! 
Unfortunately I have a problem, my electron program suppose to work on 32bit computers, but when I build my electron app with
`electron-builder --win --ia32`
in order to support 32bit computers, I got error when I try to run the app:

```
A JavaScript error occured in the main proccess

Uncaught Exception:
Error: Invalid or incompatible cached data (cachedDataRejected)
at Object.Module._extensions.<computed> [as .jsc]
........
```

when I build my app with electron-builder --win, it works fine.
I did like the electron example in the repo.

please help

**Comment by OsamaAbbas** [comment] 2021-01-12 11:51
Are you sure that the `.jsc` files were generated using the same `ia32` electron binaries?

**Comment by OsamaAbbas** [comment] 2021-01-12 12:16
I just tried electron ia32, and it works just fine with bytenode using our basic example and electron-quick-start example.

I'm closing this issue now as it is not related to bytenode. If you want more help, please provide a complete reproducible example, with clear steps to reproduce your issue.

**Comment by alonado** [comment] 2021-01-12 12:17
@OsamaAbbas thanks!
I built the jsc file from the dist execute file (not from debug) after I used
`electron-builder --win --ia32`
and now the jsc file, which probably uses the ia32 electron binaries , works!

now I have another problem, when I built jsc from a js that webpack built, and then open the app, nothing happens.
how can I built a whole electron application which has many files and directories by ByteNode?
your electron example in the repo built only one file

**Closed by OsamaAbbas** 2021-01-12 12:16 UTC

**Comment by OsamaAbbas** [comment] 2021-01-12 12:29
This is a real issue that bytenode does not deal with, due to its minimal nature.

You have to find your own approach and setup to use bytenode in a more complex scenarios. I hope that I can find some time to work on this aspect.

Also, webpack is gigantically complex, and every thing it touches becomes a total mess. Keep in mind that webpack hijacks the require system itself and put every thing inside its bundle (and you can't put the `jsc` files inside webpack bundle, of course). So, again, you will have to find you own solution to make bytenode work in this environement.

**Comment by alonado** [comment] 2021-01-12 12:35
@OsamaAbbas thanks!

I removed the obfuscator from webpack, and did webpack to the whole project without obfuscator and then built the jsc from 32bit app, and it seems to work fine!

should I be worry that webpack might broke something?

**Comment by OsamaAbbas** [comment] 2021-01-12 12:40
I'm not sure.

If by obfuscator you mean `javascript-obfuscator`, which produces huge files, I suspect it might be the issue here. I'm not sure here too, but I guess there will be a limit to the v8 bytecode. I have to look into v8 source code to figure out what this limit might be, but I guess it is there and I guess too that `javascript-obfuscator` produces huge files that exceed this limit.

You don't need to use a complex obfuscator. You can use uglify-js and the like.

**Comment by alonado** [comment] 2021-01-12 12:43
@OsamaAbbas I think that I dont need any obfuscator because I want to use your repo instead..

so my question is, if I dont use any webpack plugings and obfuscator, and do webpack in order to make one file for the whole project, and then build a jsc from this file.. should I be worry that something might break in my app?

**Comment by OsamaAbbas** [comment] 2021-01-12 14:12
My answer would be: no, webpack should not break your app. Just make sure to set `target: 'node'` in your bundle options.

If you encounter a problem with webpack bundle, open a new issue for it.

Finally, check out my other repository `enpaki`, but it is very minimal tool, so if you want more complex solution you should stick with webpack.

**Comment by alonado** [comment] 2021-01-12 14:16
@OsamaAbbas thankssss!!!
by the way, you replied that "I just tried electron ia32, and it works" ........
how did you manage to build a 32bit jsc without building a dist version like I did?

**Comment by OsamaAbbas** [comment] 2021-01-12 14:37
I used the plain electron, without electron builder nor electron webpack. Just the plain electron and I put my app inside `resources/app` folder, besides the `default_app.asar` file.

**Comment by alonado** [comment] 2021-01-12 14:38
@OsamaAbbas  thanks! 👍 🥇

**Comment by Constaline** [comment] 2021-04-27 01:50
> @OsamaAbbas thankssss!!!
> by the way, you replied that "I just tried electron ia32, and it works" ........
> how did you manage to build a 32bit jsc without building a dist version and then build a jsc from this version like I did?

if you are using electron-builder , maybe you can put `jsc` out of  `app.asar` .

**Comment by moeelbadri** [comment] 2025-11-09 21:42
for anyone coming for this issue
bun add -d electron --arch=ia32
ucan install it in another project / folder so it wont affect ur current electron 
copy the electron folder from the nodemodules
paste it in ur project and make sure to change the name to smth else e.g. electron-bits32
simply  in defineConfig in electron vite config
process.env.ELECTRON_EXEC_PATH = './node_modules/electron-bits32/dist/electron.exe'
simply like that
bun run build && electron-builder --win --ia32 --dir
dont forget to set the arch ia32 for electron-builder too
good luck!
