### ISSUE TITLE
fail test - bytenode, ncc, fastify ?

### ISSUE THREAD

**Issue by yavorski** [OsamaAbbas/bytenode#34] opened 2019-09-30 20:57 UTC
```bash
#!/usr/bin/env bash

export __TEST_DIR__="bytenode-ncc-fastify-test"

mkdir $__TEST_DIR__
cd $__TEST_DIR__

npm init --yes
npm i fastify -E
npm i bytenode @zeit/ncc -E -D

touch index.js

read -r -d '' INDEX_JS << EOF
  'use strict';
  const build = require('fastify');
  const server = build({ logger: true });
  server.all('/', async () => ({ ok: 'ok' }));
  (async () => await server.listen())();
EOF

echo $INDEX_JS > index.js

npx @zeit/ncc build index.js --out dist
npx bytenode --compile dist/index.js

# this should run?
# but it does not...
# npx bytenode $__TEST_DIR__/dist/index.jsc
npx bytenode dist/index.jsc

# Error =>
# undefined:6
#     ?
#
# SyntaxError: Invalid or unexpected token
#     at Function (<anonymous>)
#     at build (evalmachine.<anonymous>:1:70996)
#     at Object.560 (evalmachine.<anonymous>:1:521710)
#     at __webpack_require__ (evalmachine.<anonymous>:1:769)
#     at Object.360 (evalmachine.<anonymous>:1:395429)
#     at __webpack_require__ (evalmachine.<anonymous>:1:769)
#     at Object.104 (evalmachine.<anonymous>:1:66439)
#     at __webpack_require__ (evalmachine.<anonymous>:1:769)
#     at startup (evalmachine.<anonymous>:1:1228)
#     at evalmachine.<anonymous>:1:1390


#### this however runs ok
####
#### node dist/index.js
#### node $__TEST_DIR__/dist/index.js
#### node ./bytenode-ncc-fastify-test/dist/index.js
```

**Comment by OsamaAbbas** [comment] 2019-10-01 04:47
After a painful investigation, it seems that the issue lies in `fast-json-stringify` package.

From the package README file:
> fast-json-stringify is significantly faster than JSON.stringify() for small payloads. Its performance advantage shrinks as your payload grows. It pairs well with flatstr, which triggers a **V8 optimization** that improves performance when eventually converting the string to a Buffer.

So, this might be the cause of the issue. I have not figured out the exact reason why it does not play nice with bytenode. Still investigating.

This is the portion that causes the error by the way:

![image](https://user-images.githubusercontent.com/3346502/65934897-05f67580-e452-11e9-8dc0-0e20497e21dd.png)

**Comment by OsamaAbbas** [comment] 2019-10-01 07:52
Found it.

Here https://github.com/fastify/fast-json-stringify/blob/master/index.js#L53-L62 :

```javascript
    code += `
    ${$asString.toString()}
    ${$asStringNullable.toString()}
    ${$asStringSmall.toString()}
    ${$asNumber.toString()}
    ${$asNumberNullable.toString()}
    ${$asIntegerNullable.toString()}
    ${$asNull.toString()}
    ${$asBoolean.toString()}
    ${$asBooleanNullable.toString()}
```

The generated code uses `.toString();` function dynamically. Bytenode removes the source code alltogether, so when you call `.toString()` on any function all you will get is an empty string (or, to be more accurate, a series of zero-width spaces).

So, in principle you can't use bytenode to protect a code that relies on `Function.prototype.toString` function. Protection here means no [dynamic] access to the function source code, which contradicts -in principle- what `fast-json-stringify` is trying to do.

**Comment by yavorski** [comment] 2019-10-01 18:36
Wow nice thanks! 
Makes sense now.

**Comment by OsamaAbbas** [comment] 2019-10-01 22:01
I will add this to the "known limitations" in the README file soon.

Closing now.

**Closed by OsamaAbbas** 2019-10-01 22:01 UTC

**Comment by Nihiue** [comment] 2021-03-26 06:49
I got the same issue,  some web framework dynamically loads its components, and uses toString to judge whether a class is loaded, which requires operator `new` to init.

see: https://github.com/miguelmota/is-class/blob/master/is-class.js#L13

I am digging into v8 to find some workaround.
