### ISSUE TITLE
can bytenode have like sourcemap ability?

### ISSUE THREAD

**Issue by zimengle** [OsamaAbbas/bytenode#60] opened 2020-06-01 03:57 UTC
i wanna get correct pos from jsc exception,so that i can analyze exception and fix it,thx

this is a exception from jsc
```bash
TypeError: undefined is not a function
    at /Users/zimengle/Workspace/bytenode/examples/no-module-flag/script.js:1:62
    at Script.runInThisContext (vm.js:126:20)
    at runBytecode (/Users/zimengle/Workspace/bytenode/index.js:105:17)
    at Object.runBytecodeFile (/Users/zimengle/Workspace/bytenode/index.js:167:10)
    at Object.<anonymous> (/Users/zimengle/Workspace/bytenode/examples/no-module-flag/main.js:5:10)
    at Module._compile (internal/modules/cjs/loader.js:869:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:880:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:932:10)
```

this is a exception from js

```bash
TypeError: a.like is not a function
    at Object.<anonymous> (/Users/zimengle/Workspace/bytenode/examples/no-module-flag/script.js:6:3)
    at Module._compile (internal/modules/cjs/loader.js:869:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:880:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:932:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by s100** [comment] 2020-06-05 10:48
This is likely a problem in your source JavaScript, not `bytenode`. Try running the same code but use the source JavaScript file instead of the compiled bytecode file.

**Comment by OsamaAbbas** [comment] 2020-06-08 07:46
Sorry for the late reply.

I really don't see the need for that, nor bytenode can provide such a feature. Bytenode is a fairly thin layer over node.js built-in functions.

You should debug your `js` files. If you have a reproducible example where the JavaScript file works and the `.jsc` does not, please open another issue (Many users have done so already, so the possibility is there. Please check the known limitations in the README.md file).

Also, it seems that you are trying a modified version of `no-module-flag` example. I just tried it now and it works in both node 12.x.x and 14.x.x.

**Comment by delewis13** [comment] 2020-10-11 02:55
@OsamaAbbas 

First off thanks for this great library! I'm looking at using it to provide security to my src code for an Electron + webpack project.

As per the OP, I am also interested in the possibility of source-maps. 

> I really don't see the need for that

In my case, it is for integration with tools such as Sentry & FullStory, which make use of source-maps to help developers understand the errors that end users are encountering.

> nor bytenode can provide such a feature

That's a shame but understandable. I'm just wondering if I could pick your brain a little on some good strategies on triaging issues that end-users are experiencing? Just have to go from error messages without any code-line references?

**Comment by OsamaAbbas** [comment] 2020-10-13 04:50
Could you please elaborate on your use-case?

Also, `.jsc` files are binary files, not plain texts. How could you indicate where is the source map in it for the dev tools to detect it? Dev tools expect `sourceMappingURL` line, how can you give them that in a binary file that they don't even read or access? (also remember, all `.jsc` are required and parsed by node itself, not the browser).

**Comment by OsamaAbbas** [comment] 2020-10-14 17:51
I'm opening this issue because, after @delewis13 comment, I tried some approaches that can bring source map ability to bytenode. The solution in my mind now is not that straightforward, so I think it needs some consideration and discussion before I implement it.

First, do we really need this feature?

Second,

The proposed solution will be based on the fact that the dummy code, that bytenode inserts in place of the original source code, is basically just one line. It consists of `zero length space` character, repeated as many times as the original code.

So, the only way for the source map to work is when the plain text version of the code (i.e. the `.js` file) is minified to one-line file. No `\n` will be allowed. No problem here so far. We can use `uglify-js` api to achieve both: minifying the code AND generating the source map file itself. (this means that bytenode will have `uglify-js` as a dependency).

The problem is how we will use that source map. The `.jsc` files are not text files. It is not possible to use the `sourceMappingURL` line with them. The only solution I have found for this is to use `source-map-support` library, but it must be edited to make it look for the source map file automatically. So, instead of looking for `sourceMappingURL` line, we will change its functionality to just look for `server.js.map` whenever bytenode tries to run `server.jsc` file. That `server.js.map` was generated by `uglify-js` to map the minified version with the original file `server.js`.

What do you think of this approach?
Again, do we really need this feature?
For me personally, I like the minimalist aspect of bytenode. Being a zero-dependency library means much less to worry about.

**Comment by delewis13** [comment] 2020-10-15 12:13
Thanks for the consideration @OsamaAbbas !

To preface this, i'm a junior developer with not much experience working with source-maps and no real understanding of the mechanics of bytenode, so everything should be taken with a grain of salt!

> Could you please elaborate on your use-case?

I currently use webpack to bundle my files and generate source maps. These source maps get uploaded to sentry.io, and subsequently any uncaught errors experienced by users are reported to sentry. With the source maps uploaded, these error reports are accompanied by a useful stack trace & the particular offending line of code, mapped back to src. PFA screenshot [have only included a small portion of the page / stack trace] :)

> First, do we really need this feature?

Well I can only speak from my POV from this, but for me the usage of sentry.io [and whatever similar tools that must exist to help debugging in production] takes precedence over the security offered by bytenode. That said, it's entirely possible i'm misunderstanding something - i'm just working with these tools for the first time - maybe the sourcemaps aren't as useful as I anticipate.

Definitely would be good to get the input from others, as I can imagine that it would be a complex undertaking.

> What do you think of this approach?

Unfortunately my understanding of sourcemaps & bytenode is not good enough to comment!

**Comment by OsamaAbbas** [comment] 2020-12-15 07:24
I will close this issue for now. Hopefully I will come back again next year to see what can be implemented. I did some experiments to check whether the idea will work or not, but there is still some work to be done.

Thank you for your understanding.

**Closed by OsamaAbbas** 2020-12-15 07:24 UTC
Labels: enhancement

**Comment by Zhxhh** [comment] 2021-06-11 16:07
I made some work in order to support get correct exception location, see https://github.com/Zhxhh/bytenode.Maybe you can see whether it helps.

**Comment by OsamaAbbas** [comment] 2021-06-13 02:11
Storing the dummy code inside the `.jsc` files is something that I don't like that much. Also, it will break the backward compatibility with any `.jsc` files that were compiled using the current version of bytenode.

I have already mentioned another cleaner way of achieving this goal:

> The proposed solution will be based on the fact that the dummy code, that bytenode inserts in place of the original source code, is basically just one line. It consists of `zero length space` character, repeated as many times as the original code.
> 
> So, the only way for the source map to work is when the plain text version of the code (i.e. the `.js` file) is minified to one-line file. No `\n` will be allowed. No problem here so far. We can use `uglify-js` api to achieve both: minifying the code AND generating the source map file itself. (this means that bytenode will have `uglify-js` as a dependency).
> 
> The problem is how we will use that source map. The `.jsc` files are not text files. It is not possible to use the `sourceMappingURL` line with them. The only solution I have found for this is to use `source-map-support` library, but it must be edited to make it look for the source map file automatically. So, instead of looking for `sourceMappingURL` line, we will change its functionality to just look for `server.js.map` whenever bytenode tries to run `server.jsc` file. That `server.js.map` was generated by `uglify-js` to map the minified version with the original file `server.js`.

This is indeed doable (I did it already on my machine), but it needs some heavy dependencies, so maybe it should be done as another package.

Thank you for your suggestion.

**Comment by piranna** [comment] 2024-03-04 08:48
[Node.js has native support for source maps since v12.11.0](https://nodejs.medium.com/source-maps-in-node-js-482872b56116).

**Comment by OsamaAbbas** [comment] 2024-03-06 11:02
> [Node.js has native support for source maps since v12.11.0](https://nodejs.medium.com/source-maps-in-node-js-482872b56116).

Haven't read the post yet, but the problem, as explained earlier, is how we will use that source map. The `.jsc` files are not text files and we cannot use the `sourceMappingURL` to indicate the sourcemap file.

**Comment by piranna** [comment] 2024-03-06 11:03
> Haven't read the post yet, but the problem, as explained earlier, is how we will use that source map. The `.jsc` files are not text files and we cannot use the `sourceMappingURL` to indicate the sourcemap file.

We can pass it with a flag parameter with the path, for example...

**Comment by piranna** [comment] 2024-03-06 11:14
Source maps [spec](https://sourcemaps.info/spec.html#h.lmz475t4mvbx) dictates that the special comment is not mandatory, that they can be specified also in an HTTP header, so probably having a CLI arg or an environment variable (`BYTENODE_SOURCEMAP`, for example) with the path would work the same too.

**Comment by piranna** [comment] 2024-03-06 11:15
Or `BYTENODE_SOURCEMAPPINGURL` if you want to make it more explicit.
