### ISSUE TITLE
Bytenode breaking JSON.parse() and localStorage.getItem() functions.

### ISSUE THREAD

**Issue by JohnGeek-dev** [OsamaAbbas/bytenode#93] opened 2021-01-01 07:39 UTC
Hi there, my code breaks after compiling with bytenode and that it also breaks with javascript-obfuscator. And after long hours of debugging, I've come into conclusion that `JSON."parse()"` and `localStorage."getItem()"` cannot be altered in any way as it will not function at all. So my question is whether bytenode allows like some sort of exclusion to exclude certain codes/functions from being compiled/obfuscated in which javascript-obfuscator has like `/* javascript-obfuscator:disable */` to do so.

PS: These codes/functions are being used with Puppeteer.

```javascript
localStorages = await page.evaluate(() => JSON.parse(localStorage.getItem('websiteLocalStorage')));
```

**Comment by OsamaAbbas** [comment] 2021-01-02 09:33
My initial guess, just because you mentioned Puppeteer and `page.evaluate` function, is that the real problem is the different in the context between node and the browser.

I will look into it and get back to you. If you have a concrete reproducible example, that will help a lot.

**Comment by JohnGeek-dev** [comment] 2021-01-02 11:03
I don't think it's an issue with context as there aren't any iframes or some sort. Basically my code logs in to Nike website and then after a success login, the Puppeteer will open a new tab and goes to `https://unite.nike.com/session.html` to grab the `access_token` from the localStorage. Which basically translates to the code below:

```javascript
// After success login in Nike website
secondTab= await browser.newPage();
await secondTab.goto('https://unite.nike.com/session.html');
localStorages = await secondTab.evaluate(() => JSON.parse(localStorage.getItem('com.nike.commerce.snkrs.web.credential')));
// After compiling with bytenode, the code will just be stuck at the above line of code. But running with JS works fine.
access = await localStorages.access_token;
```

**Comment by OsamaAbbas** [comment] 2021-01-02 15:38
The difference in context is between node and the browser itself. If the function (that will be sent to `.evaluate()`) is written in plain text (i.e. `.js` file) there will be no problem. However, bytenode removes the source code completely, and the function (that will be sent to `.evaluate()`) is only there in bytecode format that is NOT accessible to the browser.

Try to remove `JSON.parse(...)` part. Instead, please put the object (I mean in a hard-coded manner). I don't think that it will work (and this will prove my point). However, if the hard-coded value works, this will disprove my point.

I'm waiting for your result.

**Comment by JohnGeek-dev** [comment] 2021-01-02 19:11
It doesn't work, moreover, to achieve what I need, the `JSON.parse()` is necessary. But anyway, I appreciate your help very much, thank you and keep up the good work!

**Comment by OsamaAbbas** [comment] 2021-01-03 16:27
So it does not work, and that proves my previous theory as I mentiomed before.

I will try some approaches to see if we can work around this issue.

By the way, I like Puppeteer and I use it a lot, but never needed to use bytenode with it.

**Comment by OsamaAbbas** [comment] 2021-01-03 16:59
Found the problem. See here: https://github.com/puppeteer/puppeteer/blob/67da1cf866703f5f581c9cce4923697ac38129ef/src/common/ExecutionContext.ts#L228

The implementation of `.evaluate()` function depends on `Function.toString()`, which does not work in principle with bytenode, because all source code is removed from the `.jsc` files.

There are some workarounds in my mind, but I need to test them first.

**Comment by OsamaAbbas** [comment] 2021-01-03 18:58
My proposed workaround is to separate the functions that need to be sent to `.evaluate()` into a separate `.js` file.

Something like this:

```JavaScript
// main.js, this file can be compiled
const evalFunctions = require('./eval-functions.js');
...
localStorages = await secondTab.evaluate(evalFunctions.xyz);
...
```

```JavaScript
// eval-functions.js, do NOT compile this file

exports.xyz = () => JSON.parse(localStorage.getItem('com.nike.commerce.snkrs.web.credential'));
```

I hope this solves your issue.

**Comment by OsamaAbbas** [comment] 2021-01-04 07:35
Another solution is to pass your statements as a string to `.evaluate()` function. It should work too.

I'm closing the issue now. It you still have a problem feel free to comment and ask for re-opening it.

**Closed by OsamaAbbas** 2021-01-04 07:35 UTC

**Comment by abowcut** [comment] 2021-09-09 03:24
> Another solution is to pass your statements as a string to `.evaluate()` function. It should work too.
> 
> I'm closing the issue now. It you still have a problem feel free to comment and ask for re-opening it.

Hi there,

Thanks for the good explanation as to why this issue occurs with puppeteer.
I believe however that your workaround has a slight issue.

You are allowed to pass instances of ElementHandle into page.evaluate function with puppeteer, however with the two workarounds that you described to use bytenode with page.evaluate I can't find a way to pass instances of ElementHandle's into page.evaluate() function calls while still compiling to usable bytenode.

So in general, is there a way to get the below code to work with bytenode?

```
const bodyHandle = await page.$('body');
const html = await page.evaluate(body => body.innerHTML, bodyHandle);
```

I very much appreciate your effort and consideration.
