### ISSUE TITLE
error when run in node 12

### ISSUE THREAD

**Issue by wanweidong** [OsamaAbbas/bytenode#19] opened 2019-05-15 15:13 UTC
```
const Koa = require('koa');
const KoaRouter = require('koa-router');
const app = new Koa();
const router = new KoaRouter();

module.exports = class HttpServer {
  start() {
    router.get('/a', async ctx => {
      ctx.body = 'a';
    });

    router.get('/b', async ctx => {
      ctx.body = 'b';
    });

    router.get('/c', async ctx => {
      ctx.body = 'c';
    });

    router.get('/d', async ctx => {
      ctx.body = 'd';
    });

    app.use(router.routes()).use(router.allowedMethods());
    app.listen(3000);
  }
};

```
it raise libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector
when compile and run in node 12 with mac 10.14 (bytenode -c app.js &&  bytenode app.jsc)
but it is ok when compile and run in node 10

change the code to 
```
const Koa = require('koa');
const KoaRouter = require('koa-router');
const app = new Koa();
const router = new KoaRouter();

module.exports = class HttpServer {
  start() {
    router.get('/a', async ctx => {
      ctx.body = 'a';
    });

    router.get('/b', async ctx => {
      ctx.body = 'b';
    });

    router.get('/c', async ctx => {
      ctx.body = 'c';
    });

    // router.get('/d', async ctx => {
    //   ctx.body = 'd';
    // });

    app.use(router.routes()).use(router.allowedMethods());
    app.listen(3000);
  }
};
```
it is ok compile and run in node 12

**Comment by OsamaAbbas** [comment] 2019-05-15 19:08
This is an extremely weird behavior :) . I believe it has nothing to do with Bytenode itself, as it does not even touch that level to cause such as error. Most likely that something was changed in v8 that caused this strange behavior.

I'll look into it and let you know if we can fix it. But honestly I believe it should be reported to Node (or v8) team, as Bytenode's code is very minimal and I can't see how it could cause this bug.

**Comment by OsamaAbbas** [comment] 2019-05-15 19:23
Also, the error indicates that it occurs in the C++ land, not in any JavaScript code (bytenode or whatever). That's why I believe it is not a bug in Bytenode itself.

Still investigating..

**Comment by OsamaAbbas** [comment] 2019-05-15 19:44
I guess I found it. V8 api was changed again. Compare [this](https://github.com/nodejs/node/blob/master/deps/v8/src/snapshot/code-serializer.h#L88-L96) with [this](https://github.com/v8/v8/blob/9bcb5eb590643db0c1f688fea316c7f1f4786a3c/src/snapshot/code-serializer.h#L103-L113).

This can be fixed in Bytenode.

Thank you for your report.

**Comment by OsamaAbbas** [comment] 2019-05-15 19:54
Fixed in Bytenode@1.1.1. Please update and let me know if it works now.

**Closed** 2019-05-15 19:54 UTC
Labels: bug

**Comment by wanweidong** [comment] 2019-05-15 23:29
Cool, it works now. thank you!

**Comment by tatumio** [comment] 2020-08-24 19:16
The same error happened with v13 to v14 migration. Or, at least, a complex project in Nest.JS running in v13 is not running in v14 with the same error.

**Comment by OsamaAbbas** [comment] 2020-08-25 10:25
> The same error happened with v13 to v14 migration. Or, at least, a complex project in Nest.JS running in v13 is not running in v14 with the same error.

Can you provide an example?

Sometimes there are some changes between major versions of node (or v8 itself) that breaks bytenode. I remember that when Node v14 was released I did some tests and it works just fine. If you have a specific case where Node v14 is broken that would help a lot.

**Comment by tatumio** [comment] 2020-08-25 10:48
I cannot detect, which of the library in my stack is responsible for this behaviour, it is quite complex. I will try to detect it.

**Comment by OsamaAbbas** [comment] 2020-08-25 10:52
Don't try. I will make a fix and send it to you to see if it solves your problem.

If you don't mind, please contact my email so I can send the proposed fix to you.
