### ISSUE TITLE
'Slice' of undefined. 

### ISSUE THREAD

**Issue by edelciomolina** [OsamaAbbas/bytenode#74] opened 2020-08-23 21:35 UTC
I´m trying to use ByteNode, following your samples to NWJS, but i´m getting this error:
 
![image](https://user-images.githubusercontent.com/4604923/90988974-56485b80-e56d-11ea-9fb5-dcb3d4d7c5bf.png)

Please, can you help me to understand if I did something wrong?
I´m using:
NODE: v10.18.1
NWJS: v0.20.2 and v0.47.3
BYTENODE: v1.1.6

> PS: I tried to understand from source code how the Slice function is used,... I do not know If I could understand well, but the principle of Slice there is just to check the version of Node, right? If am I correct, the [SEMVER](https://www.npmjs.com/package/semver) can help for this.

**Comment by OsamaAbbas** [comment] 2020-08-24 06:09
I see some confusion here.

First, the `slice` function is used inside bytenode to fix the cached data (or the compiled v8 bytecode). It has nothing to do with checking the version of Node.

Second, the code that you mentioned in your screenshot is not bytenode's code, it's from nwjs itself. I can't figure out what is wrong here without the complete project.

Please provide a minimal reproducible example, so we can investigate what went wrong.

**Comment by edelciomolina** [comment] 2020-08-24 12:33
@OsamaAbbas 
Sorry about this issue opened.
I double checked here and your sample is working fine. I yet do not know why that is happening in my project, so I'm investigating.

How is a huge project, I´m trying to isolate the uncessary to run Bytecode and check it, for now I supose that can be cache here.
I´m closing this issue.

**Comment by edelciomolina** [comment] 2020-08-24 14:10
@OsamaAbbas  I found how to reproduce the 'slide' problem...

If you runs the code with NWJS as bellow _(into index.html)_, works fine
```js
        const fs = require("fs");
        const bytenode = require("bytenode");
        const jsFile = "main.js";
        const jscFile = "main.jsc";
        if (!fs.existsSync(jscFile)) bytenode.compileFile(jsFile, jscFile);
        let content = require(`./${jscFile}`).getHTML();
        document.querySelector("#page").innerHTML = content;
```

But, if you put that same code inside a setTimeout, will break on `\bytenode\index.js:55`
```js
setTimeout(function () {
   // put here the code above
}, 3000);
```

Check the screenshot from my VSCODE 
 
![image](https://user-images.githubusercontent.com/4604923/91053963-fc41a780-e5f9-11ea-8e47-9232f87f4ccb.png)

Any ideas?

**Comment by OsamaAbbas** [comment] 2020-08-24 16:46
I will look into it and get back to you.

**Comment by OsamaAbbas** [comment] 2020-08-25 10:22
I can't reproduce that error in `NW.js v0.47.3`, and I can't run `v0.20.2` in my machine.

I have used that exact same example that we have in `examples/nwjs-hello-world`. It works either you put the code inside `setTimeout` or not.

Try again with `NW.js v0.47.3` without debugging (because debug mode breaks bytenode in Node =< 10) and see if it works.

**Comment by edelciomolina** [comment] 2020-08-26 17:39
I didn't  found any notes about problems with timeout into [NW Change Log](https://github.com/nwjs/nw.js/blob/nw47/CHANGELOG.md) but I discovered that when Bytenode is used inside a `setTimeout` works only in the NW >= 0.47.0

> Extra: None versions of NW in ia32 works, is necessary the x64 to worksfine.

Thanks Osama, to help me to find the answer!
I hope that is can help you improve the limitations description into Readme. 😅

**Comment by OsamaAbbas** [comment] 2020-08-26 20:17
I remember seeing an issue in NW.js repository that mentioned some problems with `setTimeout` (that maybe related to our problem here).

I will try some old versions of NW.js before updating README.md file with this limitation. Thank you for your help.

**Comment by OsamaAbbas** [comment] 2020-09-07 08:10
I tried many time to reproduce the error with NW.js 0.46, both normal and sdk versions, but everything works just fine, whether with your code or our default example.

So I don't see that your conclusion that: «`setTimeout` works only in the NW >= 0.47.0» is true.

I'm using linux by the way.

**Comment by OsamaAbbas** [comment] 2020-09-11 11:58
I'm closing this for now as the issue is not reproducible. Thank you.

**Closed by OsamaAbbas** 2020-09-11 11:58 UTC
